// Captive portal HTML - auto-generated, do not edit
#ifndef CAPTIVE_PORTAL_H
#define CAPTIVE_PORTAL_H

static const char CAPTIVE_PORTAL_HTML[] PROGMEM = 
"<!DOCTYPE html><html><head>"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Minerva WiFi</title>"
"<style>"
"*{box-sizing:border-box}"
"body{font-family:sans-serif;background:#0A1929;color:#5DADE2;margin:0;padding:20px}"
".c{max-width:400px;margin:0 auto;background:#0F2744;border-radius:15px;padding:20px;border:2px solid #2E86AB}"
"h1{text-align:center}"
".l{text-align:center;font-size:40px}"
"input{width:100%;padding:10px;margin:10px 0;border:2px solid #2E86AB;border-radius:8px;background:#0A1929;color:#5DADE2}"
"button{width:100%;padding:12px;background:#5DADE2;color:#0A1929;border:none;border-radius:8px;font-weight:bold}"
".n{padding:8px;background:#0A1929;border:1px solid #2E86AB;border-radius:5px;margin:5px 0;cursor:pointer}"
".s{text-align:center;padding:10px;border-radius:8px;margin-top:15px}"
".ok{background:#1a4d1a}.er{background:#4d1a1a}"
"</style></head><body>"
"<div class=\"c\">"
"<div class=\"l\">&#129417;</div>"
"<h1>Minerva WiFi</h1>"
"<div id=\"n\">Scanning...</div>"
"<form onsubmit=\"return C()\">"
"<input id=\"s\" placeholder=\"Network name\" required>"
"<input id=\"p\" type=\"password\" placeholder=\"Password\">"
"<button>Connect</button>"
"</form>"
"<div id=\"m\"></div>"
"</div>"
"<script>"
"fetch('/scan').then(r=>r.json()).then(a=>{"
"var h='';"
"for(var i=0;i<a.length;i++){"
"h+='<div class=\"n\" onclick=\"document.getElementById(\\\"s\\\").value=\\\"'+a[i].s+'\\\"\">'+a[i].s+' ('+a[i].r+')</div>';"
"}"
"document.getElementById('n').innerHTML=h||'No networks';"
"}).catch(function(){document.getElementById('n').innerHTML='Scan failed';});"
"function C(){"
"document.getElementById('m').innerHTML='<div class=\"s\">Connecting...</div>';"
"fetch('/connect?ssid='+encodeURIComponent(document.getElementById('s').value)+'&pass='+encodeURIComponent(document.getElementById('p').value))"
".then(r=>r.text()).then(t=>{"
"document.getElementById('m').innerHTML='<div class=\"s '+(t[0]=='O'?'ok':'er')+'\">'+t+'</div>';"
"});"
"return false;"
"}"
"</script></body></html>";

#endif
